### ISSUE TITLE
When training LON, the robot always rotates in place.

### ISSUE THREAD

**Issue by BJHYZJ** [hanruihua/NeuPAN#18]
![Image](https://github.com/user-attachments/assets/7fd7e2af-a8ad-437a-9fbf-79ccb224da6f)

`planner.yaml`

```
# mpc
receding: 10
step_time: 0.1
ref_speed: 4
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [1.667, 2.1]
  max_acce: [1.0, 1.0]
  length: 0.738
  width: 0.5

# initial path
ipath:
  waypoints: [[0, 3, 0], [27, 3, 0]]
  curve_style: 'dubins'   # 'dubins' or reeds or line
  min_radius: 3.0
  loop: False
  arrive_threshold: 0.1
  close_threshold: 0.1
  ind_range: 10
  arrive_index_threshold: 1
  
# proximal alternating minimization network
pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  iter_threshold: 0.5
  dune_checkpoint: 'model/diff_ranger_neupan_control/model_5000.pth'

# adjust parameters
adjust:
  q_s: 0.1
  p_u: 1.714
  eta: 10.299
  d_max: 0.477
  d_min: 0.01
  ro_obs: 10
  bk: 0.0

```

`LON_corridor.yaml`

```
# mpc
receding: 10
step_time: 0.1
ref_speed: 4
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [1.667, 2.1]
  max_acce: [1.0, 1.0]
  length: 0.738
  width: 0.5

# initial path
ipath:
  waypoints: [[0, 3, 0], [27, 3, 0]]
  curve_style: 'dubins'   # 'dubins' or reeds or line
  min_radius: 3.0
  loop: False
  arrive_threshold: 0.1
  close_threshold: 0.1
  ind_range: 10
  arrive_index_threshold: 1
  
# proximal alternating minimization network
pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  iter_threshold: 0.5
  dune_checkpoint: 'model/diff_ranger_neupan_control/model_5000.pth'

# adjust parameters
adjust:
  q_s: 0.1
  p_u: 1.714
  eta: 10.299
  d_max: 0.477
  d_min: 0.01
  ro_obs: 10
  bk: 0.0

```

What should I do?
